use_frameworks!

platform :ios, '10.0'

target 'LeafletMap_Example' do
  pod 'LeafletMap', :path => '../'

  target 'LeafletMap_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
